#!/usr/bin/env python3
"""
sentryx.report
---------------
Generates HTML and PDF vulnerability reports from a scan session's data.
HTML generation has no external dependency beyond Jinja2 templating done
inline here (no external template files to keep the package self-contained).
PDF generation uses WeasyPrint (HTML -> PDF), which requires system
libraries (see Dockerfile / README for apt packages).
"""

from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_COLOR = {
    "critical": "#7f1d1d",
    "high": "#b91c1c",
    "medium": "#b45309",
    "low": "#1d4ed8",
    "info": "#374151",
}


def _esc(value: Any) -> str:
    return html.escape(str(value)) if value is not None else ""


def render_html_report(
    session: dict[str, Any],
    vulnerabilities: list[dict[str, Any]],
    fixes_by_vuln_id: dict[int, list[dict[str, Any]]],
    ai_summary: dict[str, Any] | None,
) -> str:
    """Build a self-contained HTML report (inline CSS, no external assets)."""
    sorted_vulns = sorted(
        vulnerabilities,
        key=lambda v: SEVERITY_ORDER.get(v.get("severity", "info"), 5),
    )

    rows = []
    for v in sorted_vulns:
        sev = v.get("severity", "info")
        color = SEVERITY_COLOR.get(sev, "#374151")
        vuln_fixes = fixes_by_vuln_id.get(v["id"], [])
        fix_text = "<br>".join(_esc(f["fix_text"]) for f in vuln_fixes) or "—"
        rows.append(f"""
            <tr>
              <td><span class="sev" style="background:{color}">{_esc(sev.upper())}</span></td>
              <td>{_esc(v.get('vuln_name'))}</td>
              <td>{_esc(v.get('cve_id') or '—')}</td>
              <td>{_esc(v.get('port') or '—')}</td>
              <td>{_esc(v.get('service') or '—')}</td>
              <td>{_esc(v.get('description'))}</td>
              <td>{fix_text}</td>
            </tr>
            """)

    summary_html = ""
    if ai_summary:
        summary_risk = ai_summary.get("risk_level", "info")
        summary_color = SEVERITY_COLOR.get(summary_risk, "#374151")
        summary_html = f"""
        <div class="summary-box">
          <h2>Executive Summary</h2>
          <p><strong>Overall risk level:</strong>
             <span class="sev" style="background:{summary_color}">
               {_esc(str(summary_risk).upper())}
             </span></p>
          <p>{_esc(ai_summary.get('ai_analysis', ''))}</p>
        </div>
        """

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SENTRY-X Report — {_esc(session.get('target'))}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 40px; color: #111827; }}
  h1 {{ font-size: 22px; border-bottom: 2px solid #111827; padding-bottom: 8px; }}
  .meta {{ color: #6b7280; font-size: 13px; margin-bottom: 24px; }}
  .summary-box {{ background: #f3f4f6; border-radius: 8px; padding: 16px 20px; margin-bottom: 24px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ text-align: left; background: #111827; color: white; padding: 8px; }}
  td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }}
  .sev {{ color: white; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
  .disclaimer {{ margin-top: 32px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }}
</style>
</head>
<body>
  <h1>SENTRY-X Vulnerability Report</h1>
  <div class="meta">
    Target: <strong>{_esc(session.get('target'))}</strong> &nbsp;|&nbsp;
    Scan date: {_esc(session.get('scan_date'))} &nbsp;|&nbsp;
    Report generated: {generated_at} &nbsp;|&nbsp;
    Authorization ref: {_esc(session.get('authorization_ref') or 'NOT RECORDED')}
  </div>
  {summary_html}
  <table>
    <thead>
      <tr><th>Severity</th><th>Finding</th><th>CVE</th><th>Port</th><th>Service</th><th>Description</th><th>Remediation</th></tr>
    </thead>
    <tbody>
      {''.join(rows) if rows else '<tr><td colspan="7">No findings recorded.</td></tr>'}
    </tbody>
  </table>
  <div class="disclaimer">
    This report was generated by SENTRY-X for an authorized penetration test only.
    Findings are AI-assisted and must be validated by a qualified analyst before
    being acted upon. Distribution restricted to authorized recipients.
  </div>
</body>
</html>"""


def render_pdf_report(
    session: dict[str, Any],
    vulnerabilities: list[dict[str, Any]],
    fixes_by_vuln_id: dict[int, list[dict[str, Any]]],
    ai_summary: dict[str, Any] | None,
    output_path: str,
) -> str:
    """Render the HTML report then convert to PDF via WeasyPrint.
    Returns output_path on success. Raises ImportError with a clear message
    if WeasyPrint's system dependencies are not installed."""
    try:
        from weasyprint import HTML  # imported lazily - optional heavy dep
    except (ImportError, OSError) as exc:
        raise ImportError(
            "WeasyPrint is not available (missing Python package or system "
            "libraries - see README for apt packages). "
            f"Original error: {exc}"
        ) from exc

    html_content = render_html_report(session, vulnerabilities, fixes_by_vuln_id, ai_summary)
    HTML(string=html_content).write_pdf(output_path)
    return output_path
